name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          5.x
          6.x
          7.x
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
        TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" -p:ParallelizeTestCollections=false
    - name: Copy coverage
      run: sh copy_coverage.sh
    - name: Upload coverage to Codacy
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_TOKEN }}
        coverage-reports: coverage.xml
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
